data:
  img_size: 224
  dataset: tissue
  batch_size: 32
  resize: 224
  color: 0.4
  data_root: '/kaggle/input/tissue-raw'
model:
  baseline_model: False
  drop_path: 0.
  label_smooth: 0.
parameters:
  vote_perhead: 24 # discriminative features every attention head is voting head
  loss_alpha: 0.4
  total_num: 8
  fix: True
  dsm: True
  cam: True
  assess: False
train:
  lr: 0.0025
  epochs: 10
